In [ ]:
#create method that takes lists of values as vairables eg x1, x2, x3
#outputs list of lists with interaction coefficients and degrees eg x1*x2 

In [1]:
!pip install --user numpy
!pip install --user scipy
!pip install --user scikit-learn

    100% |████████████████████████████████| 12.1MB 85kB/s  eta 0:00:01
You are using pip version 8.1.1, however version 9.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
  Using cached scipy-1.0.0-cp27-cp27mu-manylinux1_x86_64.whl
  Using cached numpy-1.14.2-cp27-cp27mu-manylinux1_x86_64.whl
You are using pip version 8.1.1, however version 9.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
  Using cached scikit_learn-0.19.1-cp27-cp27mu-manylinux1_x86_64.whl
You are using pip version 8.1.1, however version 9.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [8]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

In [9]:
# This function takes a list of value lists as its first argument, and a list of degrees to be explored as its second
def int_terms(lst, degree):
    y = np.array(lst)
    for d in degree:
        poly = PolynomialFeatures(d)
        print 'degree: ', d
        print poly.fit_transform(y)
        print 'interaction terms: ', poly.get_feature_names()

In [10]:
if __name__=='__main__':
    int_terms([[1,2,3],[2,5,7]], [1,2])

degree:  1
[[1. 1. 2. 3.]
 [1. 2. 5. 7.]]
interaction terms:  ['1', 'x0', 'x1', 'x2']
degree:  2
[[ 1.  1.  2.  3.  1.  2.  3.  4.  6.  9.]
 [ 1.  2.  5.  7.  4. 10. 14. 25. 35. 49.]]
interaction terms:  ['1', 'x0', 'x1', 'x2', 'x0^2', 'x0 x1', 'x0 x2', 'x1^2', 'x1 x2', 'x2^2']
